import { type Bookmark } from '@bookmarks-tui/common';

const HTML_HEADER = `
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is file was generated by Bookmarks TUI (https://github.com/mvezer/bookmarks-tui) -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<meta http-equiv="Content-Security-Policy"
      content="default-src 'self'; script-src 'none'; img-src data: *; object-src 'none'"></meta>
<TITLE>Bookmarks TUI export</TITLE>
<DL><p>
`;

const HTML_FOOTER = `</DL>`;

export const generateHtml = (bookmarks: Iterable<Bookmark>): string => {
  let html = HTML_HEADER;
  for (const { url, title, modified } of bookmarks) {
    html += `      <DL><A HREF="${url}" ADD_DATE="${modified}" LAST_MODIFIED="${modified}">${title}</A>\n`;
  }
  return html + HTML_FOOTER;
};
