import { ColorSchemesKeys } from '../../colorscheme';
export const ALPHA_MAP: Record<
  'transparent' | 'opaque',
  Record<ColorSchemesKeys, number>
> = {
  transparent: {
    background: 0,
    foreground: 0xff,
    border: 0xff,
    searchBackground: 0,
    searchForeground: 0xff,
    searchBorder: 0xff,
    statusBackground: 0,
    statusForeground: 0xff,
    statusBorder: 0xff,
    selectedBackground: 0x80,
    selectedForeground: 0xff,
    deleteDialogBackground: 0xff,
    deleteDialogForeground: 0xff,
    deleteDialogBorder: 0xff,
    dialogBackground: 0x80,
    dialogForeground: 0x80,
    dialogBorder: 0x80,
    errorToastBackground: 0x80,
    errorToastForeground: 0x80,
    errorToastBorder: 0x80,
    infoToastBackground: 0x80,
    infoToastForeground: 0x80,
    infoToastBorder: 0x80,
  },
  opaque: {
    background: 0xff,
    foreground: 0xff,
    border: 0xff,
    searchBackground: 0xff,
    searchForeground: 0xff,
    searchBorder: 0xff,
    statusBackground: 0xff,
    statusForeground: 0xff,
    statusBorder: 0xff,
    selectedBackground: 0xff,
    selectedForeground: 0xff,
    deleteDialogBackground: 0xff,
    deleteDialogForeground: 0xff,
    deleteDialogBorder: 0xff,
    dialogBackground: 0xff,
    dialogForeground: 0xff,
    dialogBorder: 0xff,
    errorToastBackground: 0xff,
    errorToastForeground: 0xff,
    errorToastBorder: 0xff,
    infoToastBackground: 0xff,
    infoToastForeground: 0xff,
    infoToastBorder: 0xff,
  },
};
